WIP: Modernize
sous-chefs/windows_dhcp pull request #4
Opened 2020-02-19 20:10 UTC by tas50

This is a WIP PR to modernize this cookbook

2020-02-24 21:57 UTC, derekgroh commented
This looks good, do you think `Policyfiles` and `test kitchen` should be introduced as part of the modernization?

2020-02-24 22:47 UTC, tas50 commented
I was going to get things into Test Kitchen. I'm less worried about Berks since it's just used to depsolve the cookbooks that are needed for TK.

2020-02-25 00:26 UTC, tas50 commented
@derekgroh pretty sure this is ready at this point

2020-02-25 14:37 UTC, derekgroh requested changes
The data bag should be moved to the test folder as it isn't a core component of this resource cookbook and serves as an example.

A MIT `LICENSE` file should also be included to resolve all foodcritic warnings.

2020-02-25 14:37 UTC, derekgroh commented on .rubocop.yml
> +    - 'Vagrantfile'
This can be removed

2020-02-25 14:37 UTC, derekgroh commented on README.md
>  [![Join the chat at https://gitter.im/TAMUArch/cookbook.windows_dhcp](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/TAMUArch/cookbook.windows_dhcp?utm_source=badge&utm_medium=badge&utm
Not really part of modernize, but this isn't used or monitored so I think it should be removed as well.

2020-02-25 14:37 UTC, derekgroh commented on metadata.rb
> +chef_version     '> 14'
`issues_url` and `source_url` should be added

2020-02-25 16:55 UTC, tas50 commented on metadata.rb
> +chef_version     '> 14'
Fixed

2020-02-25 16:55 UTC, tas50 commented on README.md
>  [![Join the chat at https://gitter.im/TAMUArch/cookbook.windows_dhcp](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/TAMUArch/cookbook.windows_dhcp?utm_source=badge&utm_medium=badge&utm
Fixed

2020-02-25 16:55 UTC, tas50 commented on .rubocop.yml
> +    - 'Vagrantfile'
Fixed

2020-02-25 18:48 UTC, derekgroh commented
LGTM

2022-02-10 18:31 UTC, tas50 commented
Closing due to lack of response

2022-02-10 18:31 UTC, closed without merging